travis:
  secure:
    BINSTAR_TOKEN: txRZeviDogwT7yuLmX1JJs0r0mKI/vCQigKctYvvg4X+tCr8QkMO+w68bo2YNgdmdmzgJQ7TH9xQz8weHc7kUMJ604I+n8OcFtPnckIX6pJfiYhqZHEKgpxLz6VhukwVmEEaEnnvvbL3BerJiK7bICdDfKlEA1tad7XC9xDnT8RaA0bSlGNCBbEpt9U3nR5JjcFRkeuWC91/vmRZOW0HwDc2EJWoa0klT0Y9yLyYVeDN+Ceb2mrGhzrPZ+fggveNbh+VNsOFWfYnDrEXIwoELjW7iLZ/q8h3K0QfOrNQxLTC6lJYD156ReAT+CPjrSX3NDhJ3YmFZNCzpZ6WYB8qyktR5HkR7YSLSzChkV81lHUC3zr46AYPiU0RXN2Hwo9YXT1lFeJ64N3F6TZyGqWPBWil7GXTB4pxhftTS128i51yNpMPvbmOmVhLHzK0zb5vMNeBBmqoxUCO0Ss4d2KInlblJJ/i/gN1GtPjO3fsHYb92EyqxO3ASH73xeNzDTioqPx+zJoHa5o7G1TziYyI1RlaZN9PnA/9B6FekvLmJiVapuh2INH6gAH/94VO4Dbu4cqQVJOevo32J5q4rbnPv5IXiODBcrNLKWLyr+QLuOBP8J2n32k449oXpFWL+dFEReFjl+msQBISIUQjDY2EGcaQZskubJdiumzA0ocX38M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
